[package]
name = "multi-var_poly"
version = "0.1.0"
authors = ["KoheiAsano <kk.asano.luxy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-rational = "0.3"
num-traits = "0.2.14"
itertools = "0.10.0"